version: 2
models:
  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: order_status
        tests:
          - accepted_values:
              values: [created, approved, shipped, delivered, invoiced, processing, unavailable, canceled]
  - name: dim_customer
    columns:
      - name: customer_id
        tests: [not_null, unique]
  - name: dim_product
    columns:
      - name: product_id
        tests: [not_null, unique]
  - name: dim_seller
    columns:
      - name: seller_id
        tests: [not_null, unique]
  - name: fact_order_items
    columns:
      - name: order_id
        tests: [not_null]
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: product_id
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_id
      - name: seller_id
        tests:
          - relationships:
              to: ref('dim_seller')
              field: seller_id
  - name: fct_delivery_kpis
    columns:
      - name: order_id
        tests: [not_null]
